language: python

cache: 
  - pip
  - apt

python:
  #Python 2.7.9
  - "2.7"

services:
  - mongodb
  - redis-server
  
#addons:
#  postgresql: "9.3"  

git:
  depth: 100
  
env:
  #- GEVENT_RESOLVER=ares GEVENTARES_SERVERS=8.8.8.8
  - MONGOENGINE=PROD MONGREY_STORAGE=mongo MONGREY_DB=mongodb://localhost/mongrey_test MONGREY_CACHE=simple REDIS=0
  - MONGREY_STORAGE=sql MONGREY_DB=sqlite:////tmp/mongrey_test.db MONGREY_CACHE=simple REDIS=0
  #- MONGREY_STORAGE=sql MONGREY_DB=postgres://localhost/mongrey_test POSTGRESQL=1 MONGREY_CACHE=simple REDIS=0
  #- MONGREY_STORAGE=sql MONGREY_DB=mysql://localhost/mongrey_test MYSQL=1  MONGREY_CACHE=simple REDIS=0
  - MONGREY_STORAGE=sql MONGREY_DB=sqlite:////tmp/mongrey_test.db MONGREY_CACHE=redis://localhost REDIS=1
  - MONGOENGINE=DEV MONGREY_STORAGE=mongo MONGREY_DB=mongodb://localhost/mongrey_test MONGREY_CACHE=simple REDIS=0
  
before_install:
 - "sudo apt-get update -qq"
 - "sudo apt-get install -y build-essential ca-certificates language-pack-en python-dev cython libmysqlclient-dev libpq-dev"
 
install:
  - pip install -U pip
  - pip install coveralls 
  - pip install -r requirements/tests.txt
  - pip install -e .[full]
  - "if [[ $MONGOENGINE == 'DEV' ]]; then pip install -U pymongo https://github.com/MongoEngine/mongoengine/tarball/master; fi"

before_script:
  - sleep 5
  - env
  #- psql -c 'create database mongrey_test;' -U postgres
  #- "if [[ $MYSQL == '1' ]]; then mysql -e 'create database mongrey_test;'; fi"
  - pip freeze
  
script:
  - nosetests -s -v mongrey
  - flake8 --exit-zero mongrey

branches:
  only:
    - master
    
after_success: coveralls --verbose

notifications:
  email: true
  on_success: always
  on_failure: always